parameters:
  publish_sdk:
    type: boolean
    default: false
jobs:
  build:
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run test:integration
      - store_test_results:
          path: reports
      - run: echo publish to npm << pipeline.parameters.publish_sdk >>
      - when:
          condition: << pipeline.parameters.publish_sdk >>
          steps:
            - run: echo publishing sdk to npm
orbs:
  node: circleci/node@1.1
version: 2.1

